Matrix: Matrix.h
	g++ -std=c++20 Matrix.cpp -o Matrix

Matrix_new: Matrix_new.h
	g++ -std=c++20 Matrix_new.cpp -o Matrix_new

OverloadMatrix: OverloadMatrix.h
	g++ -std=c++20 OverloadMatrix.cpp -o OverloadMatrix

OverloadMatrix_new: OverloadMatrix_new.h
	g++ -std=c++20 OverloadMatrix_new.cpp -o OverloadMatrix_new

PSMatrix: PSMatrix.h
	g++ -std=c++20 PSMatrix.cpp -o PSMatrix

PSMatrix_new: PSMatrix_new.h
	g++ -std=c++20 PSMatrix_new.cpp -o PSMatrix_new
